language: python
python: 3.6

install:
  - pip install -r doc/zh/requirements.txt -q

script:
  - mv examples/zh doc/examples
  - cd doc/zh/
  - make html-noplot
  - make optipng

after_script:
  - cd _build/html/stable
  - touch .nojekyll
  - git init
  - git config user.name ${GH_UN}
  - git config user.email ${GH_EMAIL}
  - git add -A
  - git commit -am "$(date "+%Y-%m-%d %H:%M:%S")"
  - git push "https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git" master:${GH_BRANCH} -f

env:
  global:
    - GH_UN=jiangzhonglian
    - GH_EMAIL=jiang-s@163.com
    - GH_USER=apachecn
    - GH_REPO=scikit-learn-doc-zh
    - GH_BRANCH=gh-pages
